---
- name: Install remote facts
  hosts: all
  include_vars: lab-vars/fact-vars.yml
  # vars:
  #   remote_dir: /etc/ansible/facts.d
  #   facts_file: custom.fact
  tasks:
    - name: create remote directory
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: install new facts
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
